### ISSUE TITLE
sanitize issue for ungrouped latex2 output

### ISSUE THREAD

**Issue by SarBearSchwartz** [TysonStanley/furniture#16]
The `table1()` function does not sanitize text for ungrouped data when the option is set to `output = "latex2" `, such that the column heading `"Mean/Count (SD/%)"` will not knit due to the percentage symbol.

Instead, it should by `"Mean/Count (SD/\%)"` ...which it does correctly when the option is set to `output = "latex" `.  This output does not allow for setting the option for float position.  

The heading with the percentage symbol is not used for split/grouped tables.

**Comment by TysonStanley** [comment]
Weird you bring this up right now bc someone else just did two minutes before you! Yes, this is definitely a bug that I'll get fixed soon and then release to CRAN (I've been needing to send an update to CRAN anyway).

**Comment by TysonStanley** [comment]
Should be fixed in the GitHub version. Should release to CRAN later this week.
