### ISSUE TITLE
possible to replicate this in furniture?

### ISSUE THREAD

**Issue by ericpgreen** [TysonStanley/furniture#18]
I'm interested in trying to replicate something like [this table](https://twitter.com/healthandstats/status/1202111917734559744?s=20).

![](https://pbs.twimg.com/media/EK7CakSU4AEic6R?format=png&name=medium)

Specifically:

- putting the summary stats for numeric variables on the same row as the label
- moving mean (sd) qualifiers to row labels
- only showing 1 level of binary variables with summary stats shown on the same row

**Comment by TysonStanley** [comment]
Yes, definitely.

```r
library(furniture)
nhanes_2010 %>%
  group_by("Overweight" = overweight) %>%        # grouping variable
  table1("Age [Mean (SD)]" = age,                # list of variables with their corresponding labels
         "Health" = gen_health,
         "Sex" = gender,
         "Cancer" = cancer, 
         "Asthma" = asthma,
         test = TRUE,                            # test relationship between grouping variable and each row variable
         output = "latex2",
         type = "condense")                      # put things on same row
```

will produce that table.

**Comment by ericpgreen** [comment]
This is so good.

We're getting down to publication level pickiness here, but I'll ask anyway.

1. Possible to center heading over grouping levels only when adding a total column?

![Screenshot 2019-12-04 13 44 25](https://user-images.githubusercontent.com/546433/70171185-32ba4980-169c-11ea-82ea-15c7bd6614e2.png)

2. Possible to go landscape?

**Comment by TysonStanley** [comment]
Thanks!

Ah man... That's a bug. It should be centered just above the grouping levels, not the total column. Give me a bit to see if I can fix that really quick.

Also, there aren't any built in arguments for landscape but it should work with the LaTeX landscape environment (e.g. using the landscape environment, printing the table and then closing the landscape environment).

**Comment by TysonStanley** [comment]
Should work now in the latest developmental version of furniture.

<img width="612" alt="Screenshot 2019-12-04 12 28 04" src="https://user-images.githubusercontent.com/12206113/70174107-88d5bf80-1691-11ea-8b87-a645e730c7eb.png">
