### ISSUE TITLE
Footnotes and var_names

### ISSUE THREAD

**Issue by eniclas** [TysonStanley/furniture#24]
Hi! 

I'd like to add a superscript to a var_name to reference a footnote in a latex table. The code I'm using is the following:

\begin{table}[H]
\centering
\begin{threeparttable}
\caption[Baseline continuous covariate statistics for the analysis data set, stratified by study groups]{Baseline continuous covariate statistics for the analysis data set, stratified by study groups.}  \label{tab:anaContCovStudy} 
{\small
<<DAT-anaContCovStudy1,results='asis',dependson=c('PKinputData')>>=

anaDataF %>% distinct(ID,.keep_all=TRUE) %>% group_by(STUDYF) %>% furniture::table1("Age\\textsuperscript{a} (year)"=AGE,WT,BMI,BLDL,output="latex",total=TRUE)
@
}
\begin{tablenotes}
\item[a] Illustration of symbols in the table\\
\glstext{BLDL}: \glsdesc{BLDL};\glstext{SD}: \glsdesc{SD}%;
\end{tablenotes}
\end{threeparttable}
\end{table}

and the latex output from the table1 function is the following:

\begin{tabular}{llll}
\toprule
  & Total & RRW1001 & RRW1002\\
\midrule
 & n = 695 & n = 397 & n = 298\\
Age\textbackslash{}textsuperscript\{a\} (year) &  &  & \\
 & 64.0 (7.5) & 63.9 (8.0) & 64.2 (6.9)\\
WT &  &  & \\
 & 72.6 (8.7) & 72.4 (9.0) & 72.8 (8.3)\\
\addlinespace
BMI &  &  & \\
 & 23.4 (1.8) & 23.4 (1.8) & 23.4 (1.7)\\
BLDL &  &  & \\
 & 163.0 (31.1) & 163.1 (31.7) & 162.9 (30.4)\\
\bottomrule
\end{tabular}

It seems as if the escaped backslash is translated into an "ascii" backslash (\textbackslash{}). Is there a way to avoid this and get just a regular backslash so the output would be:
Age\textsuperscript\{a\} (year) &  &  & \\

Thanks for a great package!

/Niclas

**Comment by TysonStanley** [comment]
This is a great question. Can you try doing two backslashes? ie "Age\\textsuperscript{a} (year)" and see what that outputs?

**Comment by eniclas** [comment]
I used two backslashes but I think the message is formatted so that only one is visible. I think the same happened with your message. (Now I've used Preview to check the formatted version.) 

What I used, and what gives the output above, is this call to table1.
furniture::table1("Age\\\textsuperscript{a} (year)"=AGE,WT,BMI,BLDL,output="latex",total=TRUE)

Using only one bakslash:
furniture::table1("Age\textsuperscript{a} (year)"=AGE,WT,BMI,BLDL,output="latex",total=TRUE)
gives
Age	extsuperscript\{a\} (year) &  &  & \\\\

An alternative could be to use mathematical superscripts, $^a$, e.g. 
furniture::table1("Age$^a$ (year)"=AGE,WT,BMI,BLDL,output="latex",total=TRUE)
but that results in
Age\$\textasciicircum{}a\$ (year) &  &  & \\\\

So it seems as if special characters such as \ and ^ are changed to the ascii variants.

**Comment by TysonStanley** [comment]
Have you tried this with `output = "latex2"`?

**Comment by eniclas** [comment]
It works with latex2!!

I get exactly what I expect: Age\textsuperscript{a} (year) &   &   &  \\ 

That would solve the issue.

Anotehr question, is there anyway to get the number of missing values for numeric variables to be displayed? It's possible for factors, but I haven't seen any way for numerics.

**Comment by TysonStanley** [comment]
Great! 

This is something that is planned, but not currently available. I'll note that you'd be interested in it and will try to find time to work on it.
