### ISSUE TITLE
Working with logicals

### ISSUE THREAD

**Issue by dylanrussellmd** [TysonStanley/furniture#25]
I am unable to get `table1()` to include logicals in my table. It would be nice if simply `mean(logical_column)` was reported in the table which would actually be the proportion of `TRUE`. I have a large dataset with hundreds of logical columns representing the presence or absence of various risk factors.

**Comment by TysonStanley** [comment]
Hi @dylanrussellmd. Thanks for reaching out. You can make a small adjustment inside of `table1()` to make it work as is.

``` r
library(furniture)
library(dplyr)   # requires the updated version of dplyr
data %>%
  mutate(across(is.logical, ~as.numeric(.x)) %>%
  table1(<vars to report>)
```

This should do exactly what you are hoping. If the data set isn't too large (like more than 1 million rows) this shouldn't take hardly any time at all computationally.

**Comment by dylanrussellmd** [comment]
The only issue with this is won't that then cause `t.test` to be performed because they are now numeric instead of a `chisq.test`? Probably better just to convert them to a factor with `yes` and `no` levels.
