### ISSUE TITLE
could not find function "split_chain"

### ISSUE THREAD

**Issue by ericpgreen** [TysonStanley/furniture#27]
@TysonStanley do you get an error when you run:

```
library(tidyverse)
nhanes_2010 %>%
  group_by(asthma) %>%
  table1(age, marijuana, illicit, rehab,
         output = "text2",
         na.rm = FALSE)
```

> Error in split_chain(match.call(), env = env) :  could not find function "split_chain"

I'm running `furniture_1.9.7` and `magrittr_2.0.1`.

Possible issue [here](https://github.com/tidyverse/magrittr/issues/238#issuecomment-744657321)?

**Comment by TysonStanley** [comment]
Thanks, @ericpgreen. Yes, this has to do with the updated `magrittr`. The developmental version of `furniture` has a fix so you can install that. 

Once CRAN is off break, I’ll be sending the updated version there.

**Comment by priyapatel1** [comment]
Hello - I'm working through the R textbook that references this package. I got the same split_chain error, and I have installed the developmental version of furniture as indicated, but it's still not working. 

Here is my code and error:

```
> df %>% furniture::table1(asthma)

Error in split_chain(match.call(), env = env) : 
  could not find function "split_chain"
```

**Comment by TysonStanley** [comment]
Thanks for the heads up. Can you update to the very latest version (`v1.9.9`) and see if it works?

**Comment by kallevato** [comment]
I'm getting the same issue when trying to run RInno and `install_inno()`

I've tried searching through the answer on the [RInno github](https://github.com/ficonsulting/RInno), but it hasn't been updated since 2019.

Here's my code and error.
```R
> install_inno() 
Error in split_chain(match.call(), env = env) : could not find function "split_chain"
```

**Comment by TysonStanley** [comment]
I believe this error results from the updated `magrittr` package so the developer of the `RInno` package needs to be informed that the error is showing up in their package. 

The `furniture` package should be good with this issue with the developmental version (soon to be updated on CRAN).

**Comment by filipdeblock** [comment]
I got the same error message (Error in split_chain(match.call(), env = env) : could not find function "split_chain") and deleting the folder "00LOCK-magrittr" from the folder where I download packages (…\R\win-library\4.0) solved the issue.
